all:
	rm out/*
brackets:
	gcc src/brackets.c -o out/brackets.out
tree_height:
	gcc src/tree_height.c -o out/tree_height.out
network_simulation:
	gcc src/network_simulation.c -o out/network_simulation.out
stack_for_maxi:
	gcc src/stack_for_maxi.c -o out/stack_for_maxi.out
max_in_range:
	gcc src/max_in_range.c -o out/max_in_range
